-- MySQL Script generated by MySQL Workbench
-- Sun Jan  3 04:22:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema organizer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema organizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `organizer` DEFAULT CHARACTER SET utf8 ;
USE `organizer` ;

-- -----------------------------------------------------
-- Table `organizer`.`dashboards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizer`.`dashboards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `sort` INT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organizer`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizer`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `sort` INT NULL,
  `parent_id` INT NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tables_dashboards1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_tables_dashboards1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `organizer`.`dashboards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organizer`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizer`.`lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `sort` INT NULL,
  `parent_id` INT NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_groups_tables1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_groups_tables1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `organizer`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `organizer`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `organizer`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `done` TINYINT NOT NULL,
  `created_on` DATETIME NOT NULL,
  `modified_on` DATETIME NULL,
  `sort` INT NULL,
  `parent_id` INT NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tasks_groups_idx` (`parent_id` ASC),
  CONSTRAINT `fk_tasks_groups`
    FOREIGN KEY (`parent_id`)
    REFERENCES `organizer`.`lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `organizer`.`dashboards`
-- -----------------------------------------------------
START TRANSACTION;
USE `organizer`;
INSERT INTO `organizer`.`dashboards` (`id`, `name`, `sort`, `deleted`) VALUES (1, 'Dashboard', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `organizer`.`groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `organizer`;
INSERT INTO `organizer`.`groups` (`id`, `name`, `sort`, `parent_id`, `deleted`) VALUES (1, 'House chores', NULL, 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `organizer`.`lists`
-- -----------------------------------------------------
START TRANSACTION;
USE `organizer`;
INSERT INTO `organizer`.`lists` (`id`, `name`, `sort`, `parent_id`, `deleted`) VALUES (1, 'Daily', NULL, 1, NULL);
INSERT INTO `organizer`.`lists` (`id`, `name`, `sort`, `parent_id`, `deleted`) VALUES (2, 'Weekly', NULL, 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `organizer`.`tasks`
-- -----------------------------------------------------
START TRANSACTION;
USE `organizer`;
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (1, 'Floors cleaning', 0, '2021-01-01 03:00:03', NULL, NULL, 2, NULL);
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (2, 'Pet dog', 1, '2021-01-01 03:00:03', NULL, NULL, 1, NULL);
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (3, 'Do groceries', 0, '2021-01-01 03:00:03', NULL, NULL, 2, NULL);
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (4, 'Pet cat', 0, '2021-01-01 03:00:03', NULL, NULL, 1, NULL);
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (5, 'Read book', 0, '2021-01-01 03:00:03', NULL, NULL, 1, NULL);
INSERT INTO `organizer`.`tasks` (`id`, `content`, `done`, `created_on`, `modified_on`, `sort`, `parent_id`, `deleted`) VALUES (6, 'Watch movie', 0, '2021-01-01 03:00:03', NULL, NULL, 2, NULL);

COMMIT;

